name = "JLpeg"
uuid = "97e74182-bfe2-47a2-ae45-8df8c6895190"
authors = ["Sam Atman"]
version = "1.0.0-DEV"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
